# -*- coding: utf-8 -*-
"""FOPAG_Automatizada

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCxp-lstR6TP7E30SCQQXRHL_z15y0zH
"""

pip install pandas openpyxl

import pandas as pd
from google.colab import files
import io

def processar_pagamentos_colab():
    # 1. Upload
    print("\n Passo 1: Selecione os arquivos 'Ativos Banco' e 'Ativos Empresa'.")
    uploaded = files.upload()

    # Identificação dos arquivos
    nome_arq_banco = ""
    nome_arq_empresa = ""

    for nome_arquivo in uploaded.keys():
        if "banco" in nome_arquivo.lower():
            nome_arq_banco = nome_arquivo
        elif "empresa" in nome_arquivo.lower():
            nome_arq_empresa = nome_arquivo

    if not nome_arq_banco or not nome_arq_empresa:
        print("\nERRO: Não identifiquei os arquivos automaticamente.")
        return

    # 2. Data
    data_competencia = input("\n Passo 2: Insira a Data de Competência: ")

    try:
        print("\n Passo 3: Processando...")

        # Leitura Banco (Nome na Coluna B/Index 1, Matrícula na Coluna D/Index 3)
        df_banco = pd.read_excel(io.BytesIO(uploaded[nome_arq_banco]))
        dicionario_banco = dict(zip(
            df_banco.iloc[:, 1].astype(str).str.strip().str.upper(),
            df_banco.iloc[:, 3]
        ))

        # Leitura Empresa
        df_empresa = pd.read_excel(io.BytesIO(uploaded[nome_arq_empresa]))

        lista_final = []

        # Conferência
        for index, linha in df_empresa.iterrows():
            try:
                # Dados da Empresa
                nome_empresa_original = str(linha.iloc[1])
                nome_empresa_formatado = nome_empresa_original.strip().upper()

                cpf_empresa = linha.iloc[3]
                valor_empresa = linha.iloc[7]

                # LÓGICA DE VERIFICAÇÃO
                if nome_empresa_formatado in dicionario_banco:
                    # CASO 1: Encontrou no Banco
                    matricula = dicionario_banco[nome_empresa_formatado]
                else:
                    # CASO 2: NÃO Encontrou no Banco
                    matricula = "Não Cadastrado no Banco"

                # Adiciona na lista (funciona para os dois casos)
                lista_final.append({
                    "Nome do Beneficiário": nome_empresa_original,
                    "CPF": cpf_empresa,
                    "Valor": valor_empresa,
                    "Data de Competência": data_competencia,
                    "Matrícula": matricula # Aqui entra o número ou o aviso
                })

            except: continue

        # Resultado
        if lista_final:
            nome_saida = "Planilha_Pagamento_Final.xlsx"
            pd.DataFrame(lista_final).to_excel(nome_saida, index=False)

            print(f"\n SUCESSO! {len(lista_final)} registros processados.")
            files.download(nome_saida)
        else:
            print("\n A lista final ficou vazia.")

    except Exception as e:
        print(f"Erro: {e}")

if __name__ == "__main__":
    processar_pagamentos_colab()
